---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: openfaas
  namespace: flux-system
spec:
  chart:
    spec:
      chart: openfaas
      sourceRef:
        kind: HelmRepository
        name: openfaas
      version: 5.4.0
  interval: 1m0s
  values:
    generateBasicAuth: true
    serviceType: LoadBalancer
    operator:
      create: true
